# Python Packages and Modules

Libraries can be

- standard (always present with any Python distribution)
- third party (need to be installed)
- your own

To install third party libraries ... 

`pip install numpy`

Get full list of packages at: https://pypi.org/

## Importing

In [1]:
import math

In [2]:
math.sqrt(4.324)

2.079422996891205

In [3]:
import math as m

In [4]:
m.sqrt(4.353)

2.086384432457259

In [5]:
# from math import *
# sqrt(5.354)
# floor(43.2)
# radians(43.5)

Above approach is not recommended and considered bad practice.

In [6]:
from math import sqrt

In [7]:
sqrt(5.454)

2.335380054723428

# Numpy



- Third party library
- `pip install numpy`
- Contains a structure called "array" which
    - is fast
    - homogeneous
    - makes numerical computing fast

## How to create arrays?

Arrays
- can have homogeneous elements(contain same type)
- arranged continuously

In [8]:
import numpy as np

You can convert a tuple or a list into a numpy array.

In [9]:
a_tuple = (1,2,3)
a_list = [1,2,3]

arr1 = np.array(a_tuple)
arr2 = np.array(a_list)

In [10]:
type(arr1)

numpy.ndarray

In [11]:
type(arr2)

numpy.ndarray

In [14]:
nineteen_ones = np.ones(19)

In [15]:
nineteen_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1.])

In [16]:
nineteen_ones.dtype

dtype('float64')

In [17]:
ten_unpredictables = np.empty(10)

In [18]:
ten_unpredictables

array([           nan, 0.0000000e+000, 1.0295023e-311, 2.0236929e-320,
       0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
       0.0000000e+000, 0.0000000e+000])

In [19]:
ten_unpredictables.dtype

dtype('float64')

In [20]:
fifteen_zeros = np.zeros(15)

In [21]:
fifteen_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
fifteen_zeros.dtype

dtype('float64')

Some better / more useful functions to create arrays.

In [23]:
x = np.arange(10)

In [24]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
x1 = np.arange(5, 11)

In [26]:
x1

array([ 5,  6,  7,  8,  9, 10])

In [27]:
x2 = np.arange(5, 20, 2)

In [28]:
x2

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [29]:
y = np.linspace?

In [30]:
y = np.linspace(1, 100, 25)

In [31]:
y

array([  1.   ,   5.125,   9.25 ,  13.375,  17.5  ,  21.625,  25.75 ,
        29.875,  34.   ,  38.125,  42.25 ,  46.375,  50.5  ,  54.625,
        58.75 ,  62.875,  67.   ,  71.125,  75.25 ,  79.375,  83.5  ,
        87.625,  91.75 ,  95.875, 100.   ])

In [32]:
len(y)

25

In [38]:
z = np.logspace(1, 10, 10)

In [39]:
z

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

## Array Calculations

In [44]:
x = np.arange(1, 10)

In [45]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a_list = [1,2,3,4,5,6,7,8,9]

In [48]:
a_list + 2

TypeError: can only concatenate list (not "int") to list

In [68]:
x + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [69]:
y = np.arange(5, 14)

In [70]:
another_list = [5,6,7,8,9,10]

In [71]:
y

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [72]:
another_list

[5, 6, 7, 8, 9, 10]

In [73]:
a_list + another_list 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9, 10]

In [74]:
x + y

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22])

In [75]:
x * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [76]:
x * y

array([  5,  12,  21,  32,  45,  60,  77,  96, 117])

In [77]:
x - y

array([-4, -4, -4, -4, -4, -4, -4, -4, -4])

In [78]:
x / y

array([0.2       , 0.33333333, 0.42857143, 0.5       , 0.55555556,
       0.6       , 0.63636364, 0.66666667, 0.69230769])

In [79]:
x ** y

array([         1,         64,       2187,      65536,    1953125,
         60466176, 1977326743,          0, -754810903], dtype=int32)

For array operations, the size should match.

In [80]:
x = np.array([1,2,3,4])
y = np.array([1,2,3])

In [81]:
x + y

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

## 2-d arrays

In [82]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [83]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
x

array([1, 2, 3, 4])

Checking number of dimensions.

In [85]:
x.ndim

1

In [86]:
A.ndim

2

The shape of an array tells you number of elements in each dimension.

In [87]:
x.shape

(4,)

In [88]:
A.shape

(3, 3)

Check the data type.

In [89]:
x.dtype

dtype('int32')

In [90]:
A.dtype

dtype('int32')

Total size of the array, independent of number of dimensions.

In [91]:
x.size

4

In [92]:
A.size

9

## Some Operations

In [93]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
A.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [95]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [96]:
b = np.linspace(1, 100, 12)

In [97]:
b

array([  1.,  10.,  19.,  28.,  37.,  46.,  55.,  64.,  73.,  82.,  91.,
       100.])

In [98]:
len(b)

12

In [99]:
b.size

12

In [100]:
b.reshape(4,3)

array([[  1.,  10.,  19.],
       [ 28.,  37.,  46.],
       [ 55.,  64.,  73.],
       [ 82.,  91., 100.]])

In [101]:
b.reshape(3, 4)

array([[  1.,  10.,  19.,  28.],
       [ 37.,  46.,  55.,  64.],
       [ 73.,  82.,  91., 100.]])

In [102]:
b.reshape(2, 6)

array([[  1.,  10.,  19.,  28.,  37.,  46.],
       [ 55.,  64.,  73.,  82.,  91., 100.]])

In [103]:
b.reshape(6,2)

array([[  1.,  10.],
       [ 19.,  28.],
       [ 37.,  46.],
       [ 55.,  64.],
       [ 73.,  82.],
       [ 91., 100.]])

In [104]:
b

array([  1.,  10.,  19.,  28.,  37.,  46.,  55.,  64.,  73.,  82.,  91.,
       100.])

In [105]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
A.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
A.reshape(1,1)

ValueError: cannot reshape array of size 9 into shape (1,1)

In [109]:
A_1 = A.reshape(1,9)

In [110]:
A_1

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [111]:
A_1.shape

(1, 9)

# Indexing

In [112]:
x

array([1, 2, 3, 4])

In [113]:
x[0]

1

In [114]:
x[1]

2

In [115]:
x[-1]

4

In [116]:
x[1:3]

array([2, 3])

In [117]:
x[0:3:2]

array([1, 3])

In [118]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [120]:
A[0]

array([1, 2, 3])

In [121]:
A[0][0]

1

In [122]:
A[0,0]

1

In [123]:
A[1,2]

6

In [124]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [125]:
x

array([1, 2, 3, 4])

In [126]:
x[1] = 666

In [127]:
x

array([  1, 666,   3,   4])

In [128]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
A[2,1] = 13

In [130]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 13,  9]])

In [131]:
A[0:2, 1:]

array([[2, 3],
       [5, 6]])

In [132]:
A[0:2, 1:] = [[13,14], [15, 16]]

In [133]:
A

array([[ 1, 13, 14],
       [ 4, 15, 16],
       [ 7, 13,  9]])

In [134]:
A[0:2, 1:] = [[4,5], [6,]]

ValueError: setting an array element with a sequence.

## Broadcasting

In [135]:
A

array([[ 1, 13, 14],
       [ 4, 15, 16],
       [ 7, 13,  9]])

In [139]:
b = np.array([10,20,30])

In [140]:
b

array([10, 20, 30])

In [141]:
A + b

array([[11, 33, 44],
       [14, 35, 46],
       [17, 33, 39]])

In [142]:
b2 = np.array([10, 20, 30, 40])

In [143]:
A + b2

ValueError: operands could not be broadcast together with shapes (3,3) (4,) 

In [145]:
(A.T + b).T

array([[11, 23, 24],
       [24, 35, 36],
       [37, 43, 39]])

## Numpy's Sub-Modules!

In [151]:
np.random.normal(10, 2, (9,9))

array([[11.21475379,  7.29099873,  6.26789923,  9.51532508, 12.37134524,
         9.39466041,  8.8792113 ,  5.50404676,  9.4074641 ],
       [10.62642957,  6.25198802,  9.58899868, 10.10106387,  9.61114112,
         9.1273872 ,  9.34882452, 11.17842034, 10.42308473],
       [ 9.97480315,  8.27183032,  8.91434697, 14.58777065, 12.96966434,
         9.57033513,  7.54480886,  9.50674985,  9.65951243],
       [11.74510909,  8.72494118, 12.36288878,  8.81096368, 10.07926794,
        13.26214019,  8.36254445,  7.79928187, 12.73804621],
       [ 8.89906581, 10.29006891,  9.3809118 ,  8.65526586,  8.64657012,
         7.9372107 ,  9.02561726,  7.06490481,  8.17889467],
       [ 9.22098409,  8.18169206, 11.00919081,  8.134842  , 11.96388656,
         7.47925055,  5.87818685, 11.49683834,  9.5979362 ],
       [ 8.58752335,  8.87909844,  7.6134268 , 10.81656133,  8.37905126,
         9.18959595, 12.05415202, 12.84948022, 11.77105721],
       [13.15442823,  7.99919823, 10.23848418,  9.77118896,  7

In [153]:
np.linalg.inv(A)

array([[-0.42196532,  0.37572254, -0.01156069],
       [ 0.43930636, -0.51445087,  0.23121387],
       [-0.30635838,  0.45086705, -0.21387283]])